# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [5]:
import numpy as np

a = np.arange(12).reshape(3,4)
print('numpy array:',a)
print('list(a):', list(a))     ##只轉第一層為list
print('toliat():', a.tolist()) ##每層都轉為list

numpy array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
list(a): [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
toliat(): [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

import numpy as np

In [23]:

a = np.random.randint(10, size=6) 

print('Data: ', a)
print('維度: ', a.ndim)
print('每個維度大小: ', a.shape)
print('陣列中有幾個元素: ', a.size)
print('陣列中的資料型態: ', a.dtype)
print('陣列中每個元素所佔空間: ', a.itemsize)
print('Length: ', len(a))
print('陣列型態: ', type(a))
print('記憶體位置: ', a.data)

Data:  [9 4 8 8 6 0]
維度:  1
每個維度大小:  (6,)
陣列中有幾個元素:  6
陣列中的資料型態:  int64
陣列中每個元素所佔空間:  8
Length:  6
陣列型態:  <class 'numpy.ndarray'>
記憶體位置:  <memory at 0x7fc745d2b108>


In [24]:
b = np.random.randint(10, size=(3,4)) 

print('Data: ', b)
print('維度: ', b.ndim)
print('每個維度大小: ', b.shape)
print('陣列中有幾個元素: ', b.size)
print('陣列中的資料型態: ', b.dtype)
print('陣列中每個元素所佔空間: ', b.itemsize)
print('Length: ', len(b))
print('陣列型態: ', type(b))
print('記憶體位置: ', b.data)

Data:  [[6 7 3 8]
 [1 4 1 7]
 [3 7 2 9]]
維度:  2
每個維度大小:  (3, 4)
陣列中有幾個元素:  12
陣列中的資料型態:  int64
陣列中每個元素所佔空間:  8
Length:  3
陣列型態:  <class 'numpy.ndarray'>
記憶體位置:  <memory at 0x7fc7449a27e0>


In [25]:
c = np.random.randint(10, size=(2,3,2)) 

print('Data: ', c)
print('維度: ', c.ndim)
print('每個維度大小: ', c.shape)
print('陣列中有幾個元素: ', c.size)
print('陣列中的資料型態: ', c.dtype)
print('陣列中每個元素所佔空間: ', c.itemsize)
print('Length: ',len(c) )
print('陣列型態: ', type(c))
print('記憶體位置: ', c.data)

Data:  [[[7 3]
  [7 7]
  [0 0]]

 [[4 4]
  [6 5]
  [2 3]]]
維度:  3
每個維度大小:  (2, 3, 2)
陣列中有幾個元素:  12
陣列中的資料型態:  int64
陣列中每個元素所佔空間:  8
Length:  2
陣列型態:  <class 'numpy.ndarray'>
記憶體位置:  <memory at 0x7fc745708408>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [48]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[2, 6, 1, 2, 5, 5]
[2, 6, 1, 2, 5, 5]


In [49]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[2, 6, 4, 2], [7, 2, 3, 9], [5, 6, 3, 0]]
[array([2, 6, 4, 2]), array([7, 2, 3, 9]), array([5, 6, 3, 0])]


In [50]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[0, 4], [4, 5], [4, 9]], [[4, 7], [3, 3], [0, 4]]]
[array([[0, 4],
       [4, 5],
       [4, 9]]), array([[4, 7],
       [3, 3],
       [0, 4]])]


In [51]:
def makelist(array,appendlist,index):
    i = index - 1;
    if(i == 0):
        appendlist.append(list(array))
        return appendlist;
    else:
        for x in list(array):
            makelist(x,appendlist,i)

def tolist(iterable):
    l = list();
    ndim = iterable.ndim
    makelist(iterable,l,ndim)
    return l;
    


print(tolist(a))
print(tolist(b))
print(tolist(c))

[[2, 6, 1, 2, 5, 5]]
[[2, 6, 4, 2], [7, 2, 3, 9], [5, 6, 3, 0]]
[[0, 4], [4, 5], [4, 9], [4, 7], [3, 3], [0, 4]]
